name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - h5py
  - numpy=1.21.5
  - setuptools=61.2.0
  - netcdf4
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
      - git+https://github.com/pydata/xarray.git
